SHELL := /bin/bash
VERSION?=latest
MODEL?=LSTM_exp_Daily_1_day_lag
TASK_IMAGES:=$(shell find tasks -name Dockerfile -printf '%h ' )
#REGISTRY=base:5000

tasks/%: FORCE
        set -e ;\
        docker build -t $(MODEL)_pipeline_$(@F):$(VERSION) $@ --network=host;\
        docker tag model_pipeline_$(@F):$(VERSION) model_pipeline_$(@F):$(VERSION) ;\


images: $(TASK_IMAGES)

run: images
        ls

FORCE: ;
